# Generated by Django 4.1.3 on 2022-11-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("music_release", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="length",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="album",
            name="songs",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music_release.song",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="length",
            field=models.DurationField(),
        ),
    ]
