# Generated by Django 4.1.3 on 2022-11-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("music_release", "0002_alter_album_length_alter_album_songs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="songs",
        ),
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music_release.album",
            ),
        ),
    ]
